FROM java:8
MAINTAINER Teerasak Vichadee "iolumin@gmail.com"

VOLUME /tmp
EXPOSE 8100

ADD ${jar.baseName}-${jar.version}.jar ${project.name}.jar

# RUN bash -c 'touch /${project.name}.jar'
ENTRYPOINT ["java", "-Djava.security.egd=file:/dev/./urandom" ,"-jar", "/${project.name}.jar" ]
